//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRecruitingAgent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int AccountId { get; set; }
        public string APIKey { get; set; }
        public string APISecret { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> Expiry { get; set; }
        public string AccountName { get; set; }
        public string APIValue1 { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int RecId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual Recruiter Recruiter { get; set; }
    }
}
