//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRecruitingAgent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminKey
    {
        public int AdminKeyId { get; set; }
        public string AdminAPIKey { get; set; }
        public string AdminAPIKeySecret { get; set; }
        public string AdminAPiValue { get; set; }
        public string AdminAPIToken { get; set; }
        public Nullable<System.DateTime> Expiry { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public int AdminId { get; set; }
    
        public virtual Admin Admin { get; set; }
    }
}
