//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRecruitingAgent.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Applicant
    {
        public int ApplicantId { get; set; }
        public int JobId { get; set; }
        public int CanId { get; set; }
        public string ApplicantFullName { get; set; }
        public string Email { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> EmailSent { get; set; }
        public Nullable<bool> ConfirmationDone { get; set; }
        public Nullable<bool> IsHired { get; set; }
        public Nullable<bool> IsInterviewed { get; set; }
        public Nullable<bool> IsShortlisted { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }

        public virtual Candidate Candidate { get; set; }
        public virtual Job Job { get; set; }
    }
}
