//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRecruitingAgent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidate()
        {
            this.Applicants = new HashSet<Applicant>();
            this.CandidateQualifications = new HashSet<CandidateQualification>();
            this.CandidateSkills = new HashSet<CandidateSkill>();
        }
    
        public int CanId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Email { get; set; }
        public string MobileNumber { get; set; }
        public string SecondaryPhone { get; set; }
        public string NextofKinName { get; set; }
        public string NextofKinPhone { get; set; }
        public string InCaseOfEmergency { get; set; }
        public Nullable<int> Experience { get; set; }
        public string Qualification { get; set; }
        public string QualificationType { get; set; }
        public string Interests { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CVFile { get; set; }
        public string CVDescription { get; set; }
        public string NICFile { get; set; }
        public string DegreeFile1 { get; set; }
        public string DegreeFile2 { get; set; }
        public string DegreeFile3 { get; set; }
        public string DegreeFile4 { get; set; }
        public string PassportFile { get; set; }
        public string FatherName { get; set; }
        public string Religion { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> RecruitmentStatus { get; set; }
        public int ResumeSourceId { get; set; }
        public Nullable<int> ApplicationType { get; set; }
        public Nullable<bool> IsQualified { get; set; }
        public int RecId { get; set; }
        public Nullable<double> MarksObtained { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Applicant> Applicants { get; set; }
        public virtual Recruiter Recruiter { get; set; }
        public virtual ResumeSource ResumeSource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateQualification> CandidateQualifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateSkill> CandidateSkills { get; set; }
    }
}
