//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRecruitingAgent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateQualification
    {
        public int CanQualificationId { get; set; }
        public int QualificationId { get; set; }
        public int CanId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual Qualification Qualification { get; set; }
    }
}
