//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRecruitingAgent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CareerPage
    {
        public int Id { get; set; }
        public string Heading { get; set; }
        public string Description { get; set; }
        public int RecId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Intro { get; set; }
        public string ExternalLogo { get; set; }
    
        public virtual Recruiter Recruiter { get; set; }
    }
}
