//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRecruitingAgent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DripEmail
    {
        public int DripId { get; set; }
        public Nullable<int> JobId { get; set; }
        public Nullable<int> TemplateId { get; set; }
        public Nullable<int> ApplicantId { get; set; }
        public Nullable<int> CandidateId { get; set; }
        public Nullable<bool> IsScheduled { get; set; }
        public Nullable<System.DateTime> ScheduledDateTime { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsSentSuccess { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string EmailBodyText { get; set; }
        public string Subject { get; set; }
        public string CC { get; set; }
        public string BCC { get; set; }
        public string Attachement1 { get; set; }
        public string Attachement2 { get; set; }
        public string Attachement3 { get; set; }
        public string Attachement4 { get; set; }
        public string Link { get; set; }
        public Nullable<bool> IsBodyHtml { get; set; }
        public int RecId { get; set; }
    
        public virtual Recruiter Recruiter { get; set; }
    }
}
