//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRecruitingAgent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecSMTP
    {
        public int RecSMTPId { get; set; }
        public int RecId { get; set; }
        public string SMTP { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Network { get; set; }
        public Nullable<bool> IsSSL { get; set; }
        public string Port { get; set; }
        public string IP { get; set; }
        public string HostName { get; set; }
        public string ClientName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string SMTPKey { get; set; }
        public string SMTPValue { get; set; }
        public string Description { get; set; }
    
        public virtual Recruiter Recruiter { get; set; }
    }
}
